//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sm224testB.rc
//
#define IDS_FINDNEWDEVICE               1
#define IDS_HARDWAREINSTALL             2
#define IDS_HARDWAREUPDATE              3
#define IDC_Button_Export               3
#define IDS_NEXT                        4
#define IDC_Button_Import               4
#define IDS_FINISH                      5
#define IDS_CONINSTALL                  6
#define IDS_CANCEL                      7
#define IDS_NOWDONT                     8
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SM224TESTB_DIALOG           102
#define IDS_JUSTSCANUSB                 102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_START                       103
#define IDS_QUIT                        104
#define IDS_SETTING                     105
#define IDS_SCANUSB                     106
#define IDS_DEBUG                       107
#define IDS_FACTORYDRIVER               108
#define IDS_CONFIGHUB                   109
#define IDS_TOOLS                       110
#define IDS_DIALOGOPTION                111
#define IDS_OTHERSETTING                112
#define IDS_CONFIG                      113
#define IDS_MixFiles                    114
#define IDS_DECODECMB                   115
#define IDS_CREATEDMG                   116
#define IDS_COMPORTCONNECT              117
#define IDS_FONTS                       118
#define IDS_BUTTONHIDE                  119
#define IDS_LISTHIDE                    120
#define IDS_NUMOFBUTTON                 121
#define IDS_PROGRESS                    122
#define IDS_STATUS                      123
#define IDS_CAPACITY                    124
#define IDS_SN                          125
#define IDS_VIDPID                      126
#define IDS_FLASHID                     127
#define IDR_MAINFRAME                   128
#define IDS_BADBLOCK                    128
#define IDS_INQUIRY                     129
#define IDS_WRITEPROTECT                130
#define IDS_EXTRASETTING                131
#define IDS_ITEM                        132
#define IDS_FONTNAME                    133
#define IDD_DIALOGREADCID               134
#define IDS_PORT                        134
#define IDD_DIALOGSETTING               135
#define IDS_TESTCOUNT                   135
#define IDS_PASS                        136
#define IDS_FAIL                        137
#define IDS_CONNECT                     138
#define IDS_DISCONNECT                  139
#define IDD_DIALOGVIEWCID               140
#define IDS_MULTIPLEERASEALL            140
#define IDS_SupervisorMode              141
#define IDD_DIALOGPASS                  142
#define IDD_DIALOGSHOW                  143
#define IDD_DIALOG1                     144
#define IDD_DIALOGBURNIN                145
#define IDD_DIALOGSECTORCOUNT           146
#define IDR_MENUHUB                     147
#define IDD_DIALOGCONFIGHUB             148
#define IDC_CURSOR1                     150
#define IDD_DIALOGPRELOAD               151
#define IDC_CURSOR2                     152
#define IDD_DIALOG_SelectFlash          153
#define IDD_FontSize                    154
#define IDD_SETBTNNum                   156
#define IDD_MIXFILES                    157
#define IDD_SETTINGPAGE                 158
#define IDD_MAINPAGE                    158
#define IDD_DLG_UDiskImageCreator       159
#define IDD_DIALOG_TurnOffMU            160
#define IDD_BBInfoDialog                161
#define IDD_SETCOPYCMPDBGDLG            162
#define IDD_DIALOGExtraSetting          163
#define IDD_DIALOGLogFileSetting        164
#define IDD_SETTINGDLG                  165
#define IDD_DIALOG_IntlvSetting         166
#define IDD_PROGRESSDLG                 168
#define IDD_DIALOG_Duplicate            171
#define IDD_DIALOG_Test_ParaMeter       172
#define IDD_DIALOG_IDTABLE              174
#define IDD_DIALOG_New_Config           175
#define IDD_DIALOG_SETCHS               179
#define IDD_DIALOG_Diagnosis            180
#define IDD_DIALOG_HPAOPTION            181
#define IDD_DIALOG_QCSETTING            182
#define IDD_DIALOG_CESetting            183
#define IDD_DIALOG_SHOWBAD              186
#define IDD_DIALOG_UPSN_MAINPAGE        188
#define IDD_DIALOG_UpdateSNTool_caution 189
#define IDD_DIALOG_UPSN_MessageBox      190
#define IDD_DIALOG_UPSN_SelectTestMode  191
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_BUTTONSETTING               1002
#define IDC_EDIT54                      1002
#define IDC_STATIC_DISK                 1003
#define IDC_EDIT55                      1003
#define IDC_BUTTONDEBUG                 1004
#define IDC_EDIT56                      1004
#define IDC_EDIT3                       1005
#define IDC_EDIT_CH4_CE0                1005
#define IDC_EDIT4                       1006
#define IDC_BUTTONSCANCAPA              1006
#define IDC_MixingFiles                 1006
#define IDC_EDIT_CH5_CE0                1006
#define IDC_EDIT5                       1007
#define IDC_EDIT_CH6_CE0                1007
#define IDC_EDIT6                       1008
#define IDC_EDIT_CH7_CE0                1008
#define IDC_EDIT7                       1009
#define IDC_EDIT8                       1010
#define IDC_EDIT57                      1010
#define IDC_EDIT9                       1011
#define IDC_EDIT58                      1011
#define IDC_EDIT10                      1012
#define IDC_EDIT59                      1012
#define IDC_EDIT11                      1013
#define IDC_CHECK_MS                    1013
#define IDC_EDIT_CH4_CE1                1013
#define IDC_EDIT12                      1014
#define IDC_CHECK_SD                    1014
#define IDC_EDIT_CH5_CE1                1014
#define IDC_EDIT13                      1015
#define IDC_CHECK_CF                    1015
#define IDC_EDIT_CH6_CE1                1015
#define IDC_EDIT14                      1016
#define IDC_CHECK_SM                    1016
#define IDC_EDIT_CH7_CE1                1016
#define IDC_EDIT15                      1017
#define IDC_CHECKFLASH                  1017
#define IDC_EDIT16                      1018
#define IDC_EnableISPSEL                1018
#define IDC_EDIT17                      1019
#define IDC_EDIT_VID                    1019
#define IDC_EDIT_CHC_CE2                1019
#define IDC_EDIT18                      1020
#define IDC_EDIT_USB_VENDOR             1020
#define IDC_EDIT_CHD_CE2                1020
#define IDC_EDIT19                      1021
#define IDC_EDIT_PID                    1021
#define IDC_EDIT_CH4_CE2                1021
#define IDC_EDIT20                      1022
#define IDC_EDIT_BCD                    1022
#define IDC_EDIT_CH5_CE2                1022
#define IDC_EDIT21                      1023
#define IDC_EDIT_USB_PRODUCT            1023
#define IDC_EDIT_CH6_CE2                1023
#define IDC_EDIT22                      1024
#define IDC_CHECK3                      1024
#define IDC_EDIT_USB_SERIALNO           1024
#define IDC_CHECK_DiskReadOnly          1024
#define IDC_CHECK_EnableVista           1024
#define IDC_EDIT_CH7_CE2                1024
#define IDC_CHECK_WRITEWAIT             1024
#define IDC_CHECK_FORMAT                1024
#define IDC_EDIT23                      1025
#define IDC_COMBO1                      1025
#define IDC_COMBO_USBPOWER              1025
#define IDC_EDIT24                      1026
#define IDC_EDIT_SCSI_VENDOR            1026
#define IDC_EDIT25                      1027
#define IDC_PRETEST                     1027
#define IDC_EDIT_SCSI_PRODUCT           1027
#define IDC_EDIT26                      1028
#define IDC_WRITECID                    1028
#define IDC_EDIT_ISPFILEPATH            1028
#define IDC_EDIT_CHC_CE3                1028
#define IDC_DOWNLOADISP                 1029
#define IDC_EDIT29                      1029
#define IDC_EDIT_SCSI_VENDOR2           1029
#define IDC_EDIT_CHD_CE3                1029
#define IDC_COPYCOMPARE                 1030
#define IDC_EDIT30                      1030
#define IDC_ISPBROWSER                  1030
#define IDC_EDIT_CH4_CE3                1030
#define IDC_FORMAT                      1031
#define IDC_SAVE                        1031
#define IDC_EDIT35                      1031
#define IDC_EDIT60                      1031
#define IDC_EDIT_CH5_CE3                1031
#define ID_SAVETOFILE                   1032
#define IDC_SAVEAS                      1032
#define IDC_EDIT36                      1032
#define IDC_EDIT_CH6_CE3                1032
#define ID_BUTTONOK                     1033
#define IDC_LOADCID                     1033
#define IDC_EDIT37                      1033
#define IDC_EDIT_CH7_CE3                1033
#define IDC_BUTTONSELECTISP             1034
#define IDC_STATIC_ISP                  1034
#define IDC_EDIT38                      1034
#define IDC_CHECK10                     1035
#define IDC_EDIT_SCSI_PRODUCT2          1035
#define IDC_EDIT39                      1035
#define IDC_WMDRM                       1035
#define IDC_BUTTONSetCPCMP              1036
#define IDC_EDIT_SCSI_VENDOR3           1036
#define IDC_EDIT40                      1036
#define IDC_EDIT_CHC_CE4                1036
#define IDC_CHECK12                     1037
#define IDC_EDIT_SCSI_PRODUCT3          1037
#define IDC_AutoDateSerial              1037
#define IDC_EDIT41                      1037
#define IDC_EDIT_CHD_CE4                1037
#define IDC_CHECK13                     1038
#define IDC_EDIT_SCSI_VENDOR4           1038
#define IDC_CHK_MIXFILE                 1038
#define IDC_EDIT42                      1038
#define IDC_EDIT_CH4_CE4                1038
#define ID_STARTTEST                    1039
#define IDC_EDIT_SCSI_PRODUCT4          1039
#define IDC_EDIT43                      1039
#define IDC_EDIT_CH5_CE4                1039
#define IDC_EDIT27                      1040
#define IDC_EDIT_SCSI_VENDOR5           1040
#define IDC_EDIT_CH6_CE4                1040
#define IDC_COMBO2                      1041
#define IDC_EDIT_SCSI_PRODUCT5          1041
#define IDC_EDIT44                      1041
#define IDC_PROGRESS1                   1042
#define IDC_EDIT45                      1042
#define IDC_EDIT_CH7_CE4                1042
#define IDC_EDIT46                      1043
#define IDC_EDIT28                      1044
#define IDC_NOSERIALNO                  1045
#define IDC_EDIT47                      1045
#define IDC_EDIT_CHC_CE5                1045
#define IDC_CHECK2                      1046
#define IDC_MAKEAUTORUN                 1046
#define IDC_EDIT48                      1046
#define IDC_EDIT_CHD_CE5                1046
#define IDC_COMBO4                      1047
#define IDC_EnableDownloadISP2          1047
#define IDC_EDIT49                      1047
#define IDC_EDIT_CH4_CE5                1047
#define IDC_CHECK4                      1048
#define IDC_EDIT50                      1048
#define IDC_CHECK_UDMADefault           1048
#define IDC_EDIT_CH5_CE5                1048
#define IDC_COMBO5                      1049
#define IDC_EDIT51                      1049
#define IDC_EDIT_CH6_CE5                1049
#define IDC_EDIT_SingleBB_A             1050
#define IDC_EDIT_CH7_CE5                1050
#define IDC_BUTTONF0                    1051
#define IDC_EDIT_SingleBB_B             1051
#define IDC_EDIT_CHA_CE6                1051
#define IDC_EDIT31                      1052
#define IDC_BUTTONF1                    1052
#define IDC_EDIT61                      1052
#define IDC_EDIT_CHB_CE6                1052
#define IDC_BLEXARWRITE                 1053
#define IDC_EDIT53                      1053
#define IDC_EDIT_CHC_CE6                1053
#define IDC_BLEXARREAD                  1054
#define IDC_EDIT62                      1054
#define IDC_EDIT_CHD_CE6                1054
#define IDC_BUTTONSFR                   1055
#define IDC_EDIT63                      1055
#define IDC_EDIT_CH4_CE6                1055
#define IDC_BUTTONRESET                 1056
#define IDC_EDIT64                      1056
#define IDC_EDIT_CH5_CE6                1056
#define IDC_BUTTONWRITEWPRO             1057
#define IDC_EDIT65                      1057
#define IDC_EDIT_CH6_CE6                1057
#define IDC_BUTTONWRITECID              1058
#define IDC_EDIT66                      1058
#define IDC_EDIT_CH7_CE6                1058
#define IDC_BUTTONWRITEREGISTER         1059
#define IDC_EDIT67                      1059
#define IDC_EDIT_CHA_CE7                1059
#define IDC_BUTTONWRITE                 1060
#define IDC_EDIT68                      1060
#define IDC_BUTTONREAD                  1061
#define IDC_EDIT69                      1061
#define IDC_EDIT_CHC_CE7                1061
#define IDC_BUTTOND2                    1062
#define IDC_EDIT70                      1062
#define IDC_EDIT_CHD_CE7                1062
#define IDC_BUTTONReadCardMode          1063
#define IDC_EDIT71                      1063
#define IDC_EDIT_CH4_CE7                1063
#define IDC_EDIT72                      1064
#define IDC_EDIT_CH5_CE7                1064
#define IDC_EDIT73                      1065
#define IDC_EDIT_CH6_CE7                1065
#define IDC_COMBO6                      1066
#define IDC_EDIT74                      1066
#define IDC_EDIT_CH7_CE7                1066
#define IDC_EDIT75                      1067
#define IDC_COMBO7                      1068
#define IDC_EDIT76                      1068
#define IDC_CHECK5                      1069
#define IDC_PreLoad                     1069
#define IDC_EDIT77                      1069
#define IDC_CHECK6                      1070
#define IDC_CHECKPARTIAL                1070
#define IDC_EDIT78                      1070
#define IDC_CHECK_ENABLEHPA             1070
#define IDC_EDIT79                      1071
#define IDC_EDIT80                      1072
#define IDC_EDIT81                      1073
#define IDC_CHECK11                     1074
#define IDC_CHECKAutoCapacity           1074
#define IDC_EDIT_SATAGEN                1074
#define IDC_CHECK14                     1075
#define IDC_CHK_EnableTurnOffMU         1075
#define IDC_BUTTONCDFS                  1077
#define IDC_BUTTONSELECTIMAGE           1078
#define IDC_START                       1079
#define IDC_STOP                        1080
#define IDC_EDIT32                      1081
#define IDC_BUTTONSAVEFILE              1082
#define IDC_BUTTONPRETEST               1083
#define IDC_340LBAWRITE                 1084
#define IDC_DUMPSPARE                   1085
#define IDC_BUTTONDumpIsp               1086
#define IDC_BUTTONSaveBad               1087
#define IDC_BUTTONRestoreBad            1088
#define IDC_BUTTONSaveBad2              1089
#define IDC_CHECKFACTORY                1090
#define IDC_BUTTON_DumpW12              1090
#define IDC_BUTTONCLEAR                 1091
#define IDC_CHECK_PhysicalSupport       1091
#define IDC_CHECKWIN98VIA               1092
#define IDC_CHECK_Shutdown              1092
#define IDC_BUTTONDUMP                  1093
#define IDC_BUTTONERASEALL              1094
#define IDC_RADIOOFFSET                 1095
#define IDC_RADIOAUTO                   1096
#define IDC_BUTTONSELECTFILE            1097
#define IDC_EDITPATH                    1098
#define IDC_BUTTONSELECTCID             1099
#define IDC_EDITCIDISPFOLDER            1100
#define IDC_BUTTONSELECTROM             1101
#define IDC_EDIT1SELECTROM              1102
#define IDC_EDIT33                      1103
#define IDC_EDIT_NEWBAD                 1103
#define IDC_Preload_Path                1104
#define IDC_EDIT_WMA_L                  1104
#define IDC_Select_PreLoad              1105
#define IDC_EDIT_SMV                    1105
#define IDC_EDIT34                      1106
#define IDC_Preload_Path2               1106
#define IDC_EDIT_ISPCHECKSUM            1106
#define IDC_Select_PreLoad2             1107
#define IDC_EDIT_JPEG                   1107
#define IDC_EDIT_DRM                    1108
#define IDC_STATIC_Show                 1109
#define IDC_BUTTON_CheckSum             1110
#define IDC_LIST1                       1111
#define IDC_CCSlider                    1112
#define IDC_CCPercentage                1113
#define IDC_COMBO_FontSize              1114
#define IDC_CCPercentageMB              1114
#define IDC_STATIC1                     1115
#define IDC_STATIC2                     1116
#define IDC_STATIC3                     1117
#define IDC_STATIC4                     1118
#define IDC_STATIC5                     1119
#define IDC_STATIC6                     1120
#define IDC_STATIC7                     1121
#define IDC_STATIC8                     1122
#define IDC_STATIC9                     1123
#define IDC_STATIC10                    1124
#define IDC_STATIC11                    1125
#define IDC_STATIC12                    1126
#define IDC_STATIC13                    1127
#define IDC_STATIC14                    1128
#define IDC_STATIC15                    1129
#define IDC_STATIC16                    1130
#define IDC_BUTTON_BBToFile             1131
#define IDC_BUTTON_BBFromFile           1132
#define IDC_BUTTON_DOWNLOADISP          1132
#define IDC_PROGRESSErase               1133
#define IDC_STATIC_BGN_SN               1134
#define IDC_STATIC_END_SN               1135
#define IDC_COMBO_SNLEN                 1136
#define IDC_CHARStart                   1137
#define IDC_CHARSTARTSTR                1138
#define IDC_CHARENDSTR                  1139
#define IDC_CHAREnd                     1140
#define IDC_MIX_DBF                     1141
#define IDC_EDIT_HEXCHAR                1141
#define IDC_MIX_ISP                     1142
#define IDC_MIX_PRETEST                 1143
#define IDC_BTNSEL_DBF                  1144
#define IDC_BTNSEL_ISP                  1145
#define IDC_BTNSEL_PRETEST              1146
#define IDC_BTN_MIXING                  1147
#define IDC_SelMIXEDFILE                1148
#define IDC_MIXFILE_PATH                1149
#define IDC_ReserveZoneHint             1150
#define IDC_CDROMHint                   1151
#define IDC_RemainHint                  1152
#define IDC_RADIO_TI                    1153
#define IDC_RADIO_WM                    1154
#define IDC_CHK_Select2edISP            1155
#define IDC_BTN_SelectISP2ed            1156
#define IDC_ISP2ed_Path                 1157
#define IDC_STATIC_CodecType            1158
#define IDC_STATIC_PREFIX               1159
#define IDC_EDIT_PREFIXSTR              1160
#define IDC_EDIT_POSTFIXSTR             1161
#define IDC_STATIC_POSTFIX              1162
#define IDC_EDIT_FIXEDSNSTR             1163
#define IDC_STATIC_FIXEDSN              1164
#define IDC_STATIC_PrefixLen            1165
#define IDC_STATIC_PostfixLen           1166
#define IDC_STATIC_FixedLen             1167
#define IDC_CHK_AutoIncreaseSN          1168
#define IDC_STATIC_MASK_SN              1169
#define IDC_SettingPage                 1170
#define IDC_TAB_MAIN                    1170
#define IDC_RADIO_TurnoffUpperMU        1171
#define IDC_RADIO_TurnoffBottomMU       1172
#define IDC_CHK_EnablePreloadBinary     1173
#define IDC_RADIO_TurnoffCustomMU       1173
#define IDC_BTN_SelectDir               1174
#define IDC_RADIO_TurnoffAUTOMU         1174
#define IDC_EDIT_PreloadPath            1175
#define IDC_RADIO_FATFormat             1176
#define IDC_RADIO_NonFatFormat          1177
#define IDC_EDIT_PreloadPath2           1177
#define IDC_BTN_Refresh                 1178
#define IDC_BTN_SelectDir2              1178
#define IDC_RADIO_Custom                1179
#define IDC_RADIO_Automatic             1180
#define IDC_RADIO_Fully                 1181
#define IDC_COMBO_Disk                  1182
#define IDC_STATIC_Custom               1183
#define IDC_EDIT_StartLBA               1184
#define IDC_EDIT_EndLBA                 1185
#define IDC_STATIC_StartLBA             1186
#define IDC_STATIC_EndLBA               1187
#define IDC_BUTTON_ADD1                 1188
#define IDC_BUTTON_Remove1              1189
#define IDC_BUTTON_RemoveAll            1190
#define IDC_LIST_DefaultMU              1191
#define IDC_LIST_TurnOffMU              1192
#define IDC_EDIT_MU                     1192
#define IDC_BUTTON_ClearBB              1193
#define IDERASECIDISP                   1194
#define IDC_CardMode                    1195
#define IDC_EDIT_CardMode               1197
#define IDC_RADIO_PANDS                 1199
#define IDC_RADIO_PANDPANDS             1200
#define IDC_STATIC_ModeA                1201
#define IDC_STATIC_ModeC                1202
#define IDC_STATIC_ModeA_PublicSize     1203
#define IDC_EDIT_ModeA_PublicSize       1204
#define IDC_STATIC_ModeC_PublicSize     1205
#define IDC_STATIC_ModeC_PublicAPSize   1208
#define IDC_EDIT_ModeC_PublicSize       1209
#define IDC_EDIT_ModeC_SecuritySize     1210
#define IDC_SaveBBProg                  1212
#define IDC_BUTTON_SaveBadBlock         1213
#define IDC_BUTTON_SaveUFDInfo          1214
#define IDC_CHECK_SupportServerSN       1215
#define IDC_BUTTON_ReadCIDSetting       1215
#define IDC_STATIC_IPAddress            1216
#define IDC_BUTTON_SHOWBAD              1216
#define IDC_IPADDRESS1                  1217
#define IDC_STATIC_RunCardNo            1218
#define IDC_EDIT_RunCardNumber          1219
#define IDC_STATIC_PortNo               1220
#define IDC_EDIT_ServerPort             1221
#define IDC_BUTTON_ParsingDump          1221
#define IDC_STATIC_DowngradCaption      1222
#define IDC_CHECK_FloppySupport         1223
#define IDC_CHECK_FloppyFormat          1224
#define IDC_BUTTON17                    1225
#define IDC_BUTTON_SeqScanUSB           1225
#define IDC_BUTTON_ResetCounter         1225
#define IDC_BUTTON_StepScanUSB          1226
#define IDC_STATIC_SENSOR               1227
#define IDC_BUTTON_SaveCMD              1228
#define IDC_CHECK_PLCShow               1228
#define IDC_BUTTON_LoadCMD              1229
#define IDC_CHECK_SNSSupport            1229
#define IDC_CHECK_PreloadFloppy         1230
#define IDC_BUTTON_PreloadFloppy        1231
#define IDC_EDIT_PreloadFloppy          1232
#define IDC_CHECK_FAT32Format           1233
#define IDC_BUTTON_SelectUniSNPath      1233
#define IDC_BUTTON_AddBad               1234
#define IDC_BUTTON_SelectDefaultININame 1234
#define IDC_BUTTON_CreateNew            1235
#define IDC_RADIO_321ACAGAND            1235
#define IDC_BUTTON_ParsingPage2         1235
#define IDC_RADIO_321ACMicron           1236
#define IDC_BUTTON_CompareL2P           1236
#define IDC_RADIO_321ACNR               1237
#define IDC_RADIO_321ACNR2              1238
#define IDC_RADIO_321BBNR               1238
#define IDC_RADIO_324BBHalfSize         1239
#define IDC_RADIO_324BBDashR            1240
#define IDC_RADIO_AGAND                 1240
#define IDC_EDIT_TotalMU                1241
#define IDC_RADIO_321BBHalfSize         1241
#define IDC_EDIT_PageNum                1242
#define IDC_RADIO_321BBSPECTEK          1242
#define IDC_RADIO_NonAGAND              1243
#define IDC_RADIO_324BCHalfSize         1243
#define IDC_EDIT_TotalMU2               1244
#define IDC_RADIO_324BBDashR2           1244
#define IDC_AddBadBlock                 1245
#define IDC_CreateNewBadBlock           1246
#define IDC_BUTTON_NextPage             1246
#define IDC_EDIT_TotalBB                1247
#define IDC_BUTTON_PrevPage             1247
#define IDC_EDIT_TotalBB2               1248
#define IDC_BUTTON_CMP2Files            1248
#define IDC_STATIC_BBHint               1249
#define IDC_BUTTON_NextPlane            1249
#define IDC_CHECK_OrigBB                1250
#define IDC_BUTTON_PrevPlane            1250
#define IDC_BUTTON_NextMU               1251
#define IDC_BTN_LOGSettings             1252
#define IDC_BUTTON_PrevMU               1252
#define IDC_RADIO_Default               1253
#define IDC_BUTTON_NextBlock            1253
#define IDC_BUTTON_FileSelect           1254
#define IDC_BUTTON_PrevBlock            1254
#define IDC_EDIT_LogFilePath            1255
#define IDC_BUTTON_IntlvSetting         1255
#define IDC_EDIT_Custom10               1256
#define IDC_EDIT_Custom11               1257
#define IDC_EDIT_Custom20               1258
#define IDC_EDIT_Custom21               1259
#define IDC_EDIT_Custom30               1260
#define IDC_EDIT_Custom31               1261
#define IDC_EDIT_Custom40               1262
#define IDC_EDIT_Custom41               1263
#define IDC_EDIT_Custom50               1264
#define IDC_EDIT_Custom51               1265
#define IDC_EDIT_Custom60               1266
#define IDC_EDIT_Custom61               1267
#define IDC_EDIT_Custom70               1268
#define IDC_EDIT_Custom71               1269
#define IDC_LIST_COPYCOMPARE            1270
#define IDC_EDIT_Custom80               1270
#define IDC_ADDTOLIST                   1271
#define IDC_EDIT_Custom81               1271
#define IDC_REMOVELISTITEM              1272
#define IDC_RADIO_ShortenMode           1272
#define IDC_CLEARALLLIST                1273
#define IDC_RADIO_ExtendMode            1273
#define IDC_CHECK_UniqueSN              1274
#define IDC_RADIO_Disable               1274
#define IDC_EDIT_UniqueSNPath           1275
#define IDC_SLIDER1                     1276
#define IDC_CHECK_DefaultINI            1276
#define IDC_STATIC_LBACount             1277
#define IDC_EDIT_DefaultININame         1277
#define IDC_CHECK_ReadAfterWriteComplete 1278
#define IDC_CHECK_EnableControlPort     1278
#define IDC_STATIC_SLCORMLC             1279
#define IDC_BUTTON_64Page               1280
#define IDC_BUTTON_64Page2              1281
#define IDC_EDIT_Offset                 1282
#define IDC_COMBO_MemoryAddr            1283
#define IDC_RADIO_EnableIntlv           1284
#define IDC_EDIT_Offset2                1284
#define IDC_RADIO_DisableIntlv          1285
#define IDC_COMBO_MemoryAddr2           1285
#define IDC_RADIO_FlashB                1286
#define IDC_COMBO_DBFMode               1286
#define IDC_COMBO_ADDRF800BUFNUMBER     1286
#define IDC_RADIO_FlashA                1287
#define IDC_COMBO_DBFList               1287
#define IDC_CHECK_MODEC_PUBLICAPReadOnly 1288
#define IDC_RADIO_Disable2Plane         1288
#define IDC_EDIT52                      1289
#define IDC_CHECK_ModeA_APReadOnly      1289
#define IDC_RADIO_Enable2Plane          1289
#define IDC_STATIC_Percentage           1290
#define IDC_RADIO_DisableECC            1290
#define IDC_CHECK_MODEC_PUBLICReadOnly  1290
#define IDC_BUTTON_ViewLog              1291
#define IDC_STATIC_SinglePercentage_A   1291
#define IDC_STATIC_SinglePlanePercentage 1291
#define IDC_RADIO_EnableECC             1291
#define IDC_CHECK_ModeC_PubOnly         1291
#define IDC_EDIT_LogFileName            1292
#define IDC_STATIC_SinglePercentage_B   1292
#define IDC_STATIC_PLC                  1293
#define IDC_STATIC_COMPort              1294
#define IDC_STATIC_LogFile              1295
#define IDC_CHECK_EnableComPort         1296
#define IDC_STATIC_PubLbl               1297
#define IDC_STATIC_SecLbl               1298
#define IDC_STATIC_AppLbl               1299
#define IDC_EDIT_PubLbl                 1300
#define IDC_EDIT_SecLbl                 1301
#define IDC_EDIT_AppLbl                 1302
#define IDC_STATIC_SingleBB_A           1303
#define IDC_EDIT_SecPassword            1303
#define IDC_STATIC_SingleBB_B           1304
#define IDC_STATIC_SinglePlaneBB        1304
#define IDC_EDIT_SinglePlaneBB          1305
#define IDC_STATIC_Actually             1306
#define IDC_STATIC_CardMode             1307
#define IDC_STATIC_SNSSupport           1308
#define IDC_EDIT_SinglePlaneBBDisplay   1309
#define IDC_STATIC_MP3                  1310
#define IDC_STATIC_WMA_H                1311
#define IDC_STATIC_WMA_M                1312
#define IDC_STATIC_ADPCM                1313
#define IDC_EDIT_PATTERNFILEPATH1       1314
#define IDC_STATIC_DSPVersion           1314
#define IDC_EDIT_PATTERNFILEPATH2       1315
#define IDC_BUTTON_BlockCCPattern       1315
#define IDC_STATIC_WMA_L                1315
#define IDC_EDIT_PATTERNFILEPATH3       1316
#define IDC_BUTTON_ResizeWindow         1316
#define IDC_STATIC_SMV                  1316
#define IDC_BTN_PATTERNFILE_BROWSER1    1317
#define IDC_BUTTON_StartBlockCopyCompare 1317
#define IDC_STATIC_JPEG                 1317
#define IDC_BTN_PATTERNFILE_BROWSER2    1318
#define IDC_STATIC_Status               1318
#define IDC_STATIC_DRM                  1318
#define IDC_BTN_PATTERNFILE_BROWSER3    1319
#define IDC_EDIT_Security_CIDString     1319
#define IDC_EDIT_SecurityPasswd         1320
#define IDC_BUTTON_MarkBadBlock         1321
#define IDC_CHECK_EnableManualInput     1322
#define IDC_BUTTON_DumpFullDisk         1323
#define IDC_CHECK_SelectPTest           1324
#define IDC_BUTTON_DumpAllSpareByMU     1324
#define IDC_STATIC_TotalLBA             1325
#define IDC_EDIT_TotalLBA               1326
#define IDC_PROGRESS_PowerTest          1327
#define IDC_BUTTON_FillData             1329
#define IDC_STATIC_INCPage              1331
#define IDC_COMBO_IncPage               1333
#define IDC_STATIC_Block                1334
#define IDC_DumpBlockInfo               1335
#define IDC_BUTTON_Load_LBA_File        1336
#define IDC_COMBO_ARGB                  1336
#define IDC_BUTTON_LBA_SRW_Next         1337
#define IDC_STATIC_LBASeq               1338
#define IDC_ReadFlashPage               1339
#define IDC_TREE1                       1340
#define IDC_CHECK_CDROM_Only            1341
#define IDC_BUTTON_RESTOREBADBLOCK      1342
#define IDC_RADIO1k                     1347
#define IDC_RADIO2k                     1348
#define IDC_BUTTON_Duplicate            1349
#define IDC_FLASH_SELECT                1350
#define IDC_RADIO_FAIL1                 1351
#define IDC_STATIC_FilePath             1351
#define IDC_RADIO_FAIL2                 1352
#define IDC_BUTTON_LOADCONFIG           1352
#define IDC_RADIO_METHORD_SEQ           1353
#define IDC_EDIT_INIPATH                1353
#define IDC_RADIO_METHORD_RANDOM        1354
#define IDC_LIST2                       1354
#define IDC_RADIO_FAIL3                 1355
#define IDC_EDIT_MODELNAME              1355
#define IDC_BUTTONPowerTest             1356
#define IDC_CHECK_WRITEIDTABLE          1356
#define IDC_BUTTON_SCANUSB              1357
#define IDC_BUTTON_Edit                 1358
#define IDC_CHECK_AUTOTEST              1359
#define IDC_CHECK_VISTA                 1360
#define IDC_EDIT_                       1361
#define IDC_BUTTON_NewConfig            1362
#define IDC_EDIT_NEW_CONFIG             1363
#define IDC_STATIC_QLIST                1364
#define IDC_EDIT_QLIST                  1365
#define IDC_CHECK_33V                   1366
#define IDC_CHECK_UDMA0                 1367
#define IDC_CHECK_UDMA1                 1368
#define IDC_CHECK_UDMA2                 1369
#define IDC_CHECK_UDMA3                 1370
#define IDC_CHECK_UDMA4                 1371
#define IDC_CHECK_UDMA5                 1372
#define IDC_CHECK_UDMA6                 1373
#define IDC_CHECK_PIODefault            1374
#define IDC_CHECK_PIO1                  1375
#define IDC_CHECK_PIO2                  1376
#define IDC_CHECK_PIO3                  1377
#define IDC_CHECK_PIO4                  1378
#define IDC_BUTTON_AUTOFLASH            1379
#define IDC_COMBO_INIPATH               1380
#define IDC_COMBO_INIFILE               1381
#define IDC_COMBO_DISKSIZE              1382
#define IDC_STATIC_FLASHSETNAME         1383
#define IDC_EDIT_VENDORSPEC             1384
#define IDC_CHECK_ENCHS                 1385
#define IDC_BUTTON_SETCHS               1386
#define IDC_EDIT_C                      1387
#define IDC_EDIT_H                      1388
#define IDC_EDIT_S                      1389
#define IDC_EDIT_SECTORS                1390
#define IDC_CCSliderMB                  1391
#define IDC_RADIO_CCPercentage          1392
#define IDC_RADIO_CCPercentageMB        1393
#define IDC_BUTTON_DECC                 1394
#define IDC_BUTTON_DECNT                1395
#define IDC_STATIC_NEWBAD               1396
#define IDC_BUTTON_DFECC                1397
#define IDC_STATIC_ISPCHECKSUM          1398
#define IDC_BUTTON_JumpCode             1399
#define IDC_BUTTON_FID                  1400
#define IDC_STATIC_STRONGPAGE           1401
#define IDC_COMBO_STRONGPAGE            1402
#define IDC_BUTTON_SAVEIDTABLE          1403
#define IDC_EDIT_CHA_CE0                1404
#define IDC_EDIT_CHB_CE0                1405
#define IDC_EDIT1_CHA_CE1               1405
#define IDC_EDIT_CHC_CE0                1406
#define IDC_EDIT1_CHA_CE2               1406
#define IDC_EDIT_CHD_CE0                1407
#define IDC_EDIT1_CHA_CE3               1407
#define IDC_EDIT_CHA_CE1                1408
#define IDC_EDIT1_CHA_CE4               1408
#define IDC_EDIT_CHB_CE1                1409
#define IDC_EDIT1_CHA_CE5               1409
#define IDC_EDIT_CHC_CE1                1410
#define IDC_EDIT1_CHA_CE6               1410
#define IDC_EDIT_CHD_CE1                1411
#define IDC_EDIT1_CHA_CE7               1411
#define IDC_EDIT_CHA_CE2                1412
#define IDC_EDIT1_CHB_CE1               1412
#define IDC_EDIT_CHB_CE2                1413
#define IDC_EDIT1_CHB_CE2               1413
#define IDC_EDIT_CHA_CE3                1414
#define IDC_EDIT1_CHB_CE3               1414
#define IDC_EDIT_CHB_CE3                1415
#define IDC_EDIT1_CHB_CE4               1415
#define IDC_EDIT_CHA_CE4                1416
#define IDC_EDIT1_CHB_CE5               1416
#define IDC_EDIT_CHB_CE4                1417
#define IDC_EDIT1_CHB_CE6               1417
#define IDC_EDIT_CHA_CE5                1418
#define IDC_EDIT1_CHB_CE7               1418
#define IDC_EDIT_CHB_CE5                1419
#define IDC_EDIT1_CHC_CE1               1419
#define IDC_EDIT_CHB_CE7                1420
#define IDC_EDIT1_CHC_CE2               1420
#define IDC_STATIC_CLOCK                1421
#define IDC_EDIT1_CHC_CE3               1421
#define IDC_CHECK2_DISABLE_WL           1422
#define IDC_EDIT1_CHC_CE4               1422
#define IDC_COMBO_CLOCK                 1423
#define IDC_EDIT1_CHC_CE5               1423
#define IDC_EDIT_TOTALBYTE              1424
#define IDC_EDIT1_CHC_CE6               1424
#define IDC_CHECK_READWAIT              1425
#define IDC_EDIT1_CHC_CE7               1425
#define IDC_STATIC_ADJUST               1426
#define IDC_EDIT1_CHD_CE1               1426
#define IDC_COMBO_ADJUSTBLOCK           1427
#define IDC_EDIT1_CHD_CE2               1427
#define IDC_BUTTON_K9F1G                1428
#define IDC_EDIT1_CHD_CE3               1428
#define IDC_PRESCAN                     1429
#define IDC_EDIT1_CHD_CE4               1429
#define IDC_STATIC_RESULT               1430
#define IDC_RESTOREALL                  1430
#define IDC_EDIT1_CHD_CE5               1430
#define IDC_STATIC_SIZE                 1431
#define IDC_EDIT1_CHD_CE6               1431
#define IDC_COMBO_SIZE                  1432
#define IDC_EDIT1_CHD_CE7               1432
#define IDC_CHECK_CHECKDISKSIZE         1433
#define IDC_STATIC_PATA_DRIVE           1434
#define IDC_COMBO3_PATA_DRIVE           1435
#define IDC_STATIC_PreLoad              1436
#define IDC_STATIC_StrongTxt            1437
#define IDC_STATIC_FirmwareVer          1438
#define IDC_EDIT_FirmareVer             1439
#define IDC_STATIC_SELECT_ISP           1440
#define IDC_STATIC_SELECT_ISP2          1441
#define IDC_CHECK2_ISHEX27              1441
#define IDC_BUTTON_RESTORE_BAD          1442
#define IDC_PROGRESS_BAD                1443
#define IDC_BUTTON_MANUaL               1444
#define IDC_CHECK_WRITEPRO              1445
#define IDC_AutoDateAdjust              1446
#define IDC_CHECK_ENABLESMART           1447
#define IDC_BUTTON_SAVEBIN              1448
#define IDC_BUTTON_CE                   1448
#define IDC_BUTTON_RESTOREBIN           1449
#define IDC_STATIC_CONTROLLCOMBO        1450
#define IDC_BUTTON_SAVEBIN2             1450
#define IDC_BUTTON_SAVEBIN3             1451
#define IDC_CHECKWLDELTA                1452
#define IDC_BUTTON_SAVEBIN4             1452
#define IDC_COMBO_WLDELTA               1454
#define IDC_STATIC_SPARE                1455
#define IDC_EDIT_SPARE                  1456
#define IDC_BUTTON_HPAOPTION            1457
#define IDC_CHECK_SETMAXADDRESS         1458
#define IDC_EDIT_SETMAXADDRESS          1459
#define IDC_COMBO_LOGPRESCAN            1462
#define IDC_BUTTON_SHOWBADBIN           1463
#define IDC_STATIC_DISKLABEL            1464
#define IDC_CHECK_VENDOR                1466
#define IDC_STATIC_MINISPARE            1467
#define IDC_COMBO_MINISPARE             1468
#define IDC_STATIC_MINISPAREB           1469
#define IDC_CHECK_QC                    1470
#define IDC_CHECK_QUICKERASE            1471
#define IDC_BUTTON_QCSETTING            1472
#define IDC_EDIT_CAPACITY               1473
#define IDC_EDIT_USED                   1474
#define IDC_COMBO_SecondFlash           1475
#define IDC_BUTTON_AUTOFLASH2           1476
#define IDC_BUTTON_MANUaL2              1477
#define IDC_STATIC_DISKTYPE             1478
#define IDC_STATIC_ECC                  1479
#define IDC_COMBO_ECCBIT                1480
#define IDC_STATIC_ECCBIT               1481
#define IDC_EDIT_VALIDSPARE             1482
#define IDC_CHECK_MORECHECK             1483
#define IDC_STATIC_INCBLOCK             1484
#define IDC_COMBO_INCBLOCK              1485
#define IDC_COMBO_INCCPAGE              1486
#define IDC_COMBO_INCECC                1487
#define IDC_STATIC_ECCBITSEL            1488
#define IDC_CHECK_KEEPERASE             1489
#define IDC_STATIC_SLEEPTIME            1490
#define IDC_COMBO_SLEEPTIME             1491
#define IDC_STATIC_HYBRID               1492
#define IDC_BUTTON_SETDEFAULTSEL        1493
#define IDC_STATIC_ININAME              1495
#define IDC_STATIC_SPARESTH             1497
#define IDC_COMBO_SPARESTH              1498
#define IDC_STATIC_ECCBLOCK             1499
#define IDC_CHECK_ATA8Support           1500
#define IDC_STATIC_MINIERASE            1501
#define IDC_COMBO_MINIERASE             1502
#define IDC_CHECK_ZEROMODEL             1503
#define IDC_CHECK_LOADBINVENDOR         1504
#define IDC_CHECK_DISABLETERM           1505
#define IDC_CHECK_DOSFORMAT             1506
#define IDC_CHECK_IDTABLE               1507
#define IDC_BUTTON_IDTABLE              1508
#define IDC_EDIT_IDTABLE                1509
#define IDC_CHECK_NEWBAD                1510
#define IDC_EDITNEWBAD                  1512
#define IDC_CHECK_LBA                   1513
#define IDC_EDIT_LBA                    1514
#define IDC_EDIT_PROSTR                 1515
#define IDC_EDIT_InitialBAD             1515
#define IDC_EDIT_PRODUCTIONSTR          1516
#define IDC_COMBO_ECCBIT2               1517
#define IDC_STATIC_ECC2                 1518
#define IDC_CHECK_DISINTLV              1519
#define IDC_CHECK_DIS2PLANE             1520
#define IDC_CE_CHECK1                   1521
#define IDC_EDIT_PROSTR2                1521
#define IDC_EDIT_PROSTR_NAME            1521
#define IDC_CE_CHECK2                   1522
#define IDC_CE_CHECK3                   1523
#define IDC_CE_CHECK4                   1524
#define IDC_CE_CHECK5                   1525
#define IDC_CE_CHECK6                   1526
#define IDC_CE_CHECK7                   1527
#define IDC_CE_CHECK8                   1528
#define IDC_CE_CHECK9                   1529
#define IDC_CE_CHECK10                  1530
#define IDC_CE_CHECK11                  1531
#define IDC_CE_CHECK12                  1532
#define IDC_CE_CHECK13                  1533
#define IDC_CE_CHECK14                  1534
#define IDC_CE_CHECK15                  1535
#define IDC_CE_CHECK16                  1536
#define IDC_BUTTON_CESAVE               1537
#define IDC_CHECK2_FORCEGEN1            1538
#define IDC_CHECK_EnableHIPM            1539
#define IDC_CHECK_DisCacheProgram       1540
#define IDC_STATIC_ProductStr           1541
#define IDC_CHECK_checkfirmwareVersion  1542
#define IDC_CHECK_checkUDMA5            1543
#define IDC_CHECK_MORECHECK2            1544
#define IDC_CHECK_NoCheckFlashID        1545
#define IDC_CHECK_SATADASP              1546
#define IDC_EDIT_MINISPARE              1547
#define IDC_STATIC_totalTime            1548
#define IDC_CHECK_ForceAddPage          1549
#define IDC_CHECK_DisableHDTune         1550
#define IDC_CHECK_ISPMODE               1551
#define IDC_CHECK_ForceLBA48            1552
#define IDC_EDIT1_CHA_CE0               1553
#define IDC_EDIT1_CHB_CE0               1554
#define IDC_EDIT1_CHC_CE0               1555
#define IDC_EDIT1_CHD_CE0               1556
#define IDC_EDIT_A0                     1557
#define IDC_EDIT_A1                     1558
#define IDC_CHECK_InitialBAD            1558
#define IDC_EDIT_A2                     1559
#define IDC_CHECKReportECCError         1559
#define IDC_EDIT_A3                     1560
#define IDC_LIST_SNUpdatedTool          1560
#define IDC_EDIT_A4                     1561
#define ID_Start                        1561
#define IDC_EDIT_A5                     1562
#define ID_Quit                         1562
#define IDC_EDIT_A6                     1563
#define IDC_BUTTON_ScanDrive            1563
#define IDC_EDIT_A7                     1564
#define IDC_EDIT_InputSN                1564
#define IDC_EDIT_B0                     1565
#define ID_Retry                        1565
#define IDC_BUTTON_SetSN                1565
#define IDC_EDIT_B1                     1566
#define IDC_STATIC_Caution              1566
#define IDC_EDIT_B2                     1567
#define ID_UPSN_MSGBOX_OK               1567
#define IDC_EDIT_B3                     1568
#define IDC_STATIC_MEG1                 1568
#define IDC_EDIT_B4                     1569
#define IDC_STATIC_MEG2                 1569
#define IDC_BUTTON_SNupdateNverify      1569
#define IDC_EDIT_B5                     1570
#define IDC_STATIC_MEG3                 1570
#define IDC_BUTTON_SNverifyOnly         1570
#define IDC_EDIT_B6                     1571
#define IDC_STATIC_CurrentCnt           1571
#define IDC_EDIT_B7                     1572
#define IDC_STATIC_LimitCnt             1572
#define IDC_BUTTON_ClearCnt             1573
#define IDC_STATIC_caution1             1576
#define IDC_EDIT_StatusA                1577
#define IDC_TESTMODULE                  1580
#define IDC_EDIT_C0                     1581
#define IDC_EDIT_C1                     1582
#define IDC_STATIC_TestModule3          1582
#define IDC_EDIT_C2                     1583
#define IDC_STATIC_TestModule4          1583
#define IDC_FWREV                       1583
#define IDC_EDIT_C3                     1584
#define IDC_EDIT_C4                     1585
#define IDC_EDIT_C5                     1586
#define IDC_EDIT_C6                     1587
#define IDC_EDIT_C7                     1588
#define IDC_EDIT_D0                     1589
#define IDC_EDIT_D1                     1590
#define IDC_EDIT_D2                     1591
#define IDC_EDIT_D3                     1592
#define IDC_EDIT_D4                     1593
#define IDC_EDIT_D5                     1594
#define IDC_EDIT_D6                     1595
#define IDC_EDIT_D7                     1596
#define IDC_CHECK1                      2015
#define IDC_BUTTONREADCID               2019
#define IDC_BUTTONREADWPRO              2020
#define IDC_BUTTONDumpLink              2021
#define IDC_BUTTONDUMPINFO              2022
#define IDC_BUTTONREADMEMORY            2023
#define IDC_BUTTONREADFLASH             2024
#define IDC_BUTTONRAMTEST               2025
#define IDC_BUTTONROMTEST               2026
#define IDC_BUTTONERASEFLASH            2027
#define IDC_BUTTONWRITEFLASH            2028
#define IDC_BUTTONWRITEMEMORY           2029
#define IDC_BUTTONOPENFILE              2030
#define IDC_BUTTONREADPAR               2031
#define IDC_BUTTONREADEPROM             2032
#define IDC_BUTTONWRITEEPROM            2033
#define IDC_BUTTON368ISP                2034
#define IDC_BUTTONPAR368                2035
#define IDC_BUTTONCLOSE                 2036
#define IDC_BUTTONSEND                  2037
#define ID_STATIC_1                     2038
#define IDC_BUTTON0                     2200
#define IDC_BUTTON1                     2201
#define IDC_BUTTON2                     2202
#define IDC_BUTTON3                     2203
#define IDC_BUTTON4                     2204
#define IDC_BUTTON5                     2205
#define IDC_BUTTON6                     2206
#define IDC_BUTTON7                     2207
#define IDC_BUTTON8                     2208
#define IDC_BUTTON9                     2209
#define IDC_BUTTON10                    2210
#define IDC_BUTTON11                    2211
#define IDC_BUTTON12                    2212
#define IDC_BUTTON13                    2213
#define IDC_BUTTON14                    2214
#define IDC_BUTTON15                    2215
#define IDC_BUTTON16                    2216
#define IDC_BUTTON18                    2217
#define IDC_BUTTON19                    2218
#define IDC_BUTTONSELECTPTest           3001
#define IDC_RADIO1                      4000
#define IDC_RADIO2                      4001
#define IDC_RADIO3                      4002
#define IDC_RADIO4                      4003
#define IDC_RADIO5                      4004
#define IDC_RADIO6                      4005
#define IDC_RADIO7                      4006
#define IDC_RADIO8                      4007
#define IDC_RADIO9                      4008
#define IDC_RADIO10                     4009
#define IDC_RADIO11                     4010
#define IDC_RADIO12                     4011
#define IDC_RADIO13                     4012
#define IDC_RADIO14                     4013
#define IDC_RADIO15                     4014
#define IDC_RADIO16                     4015
#define IDC_CHECK_PIO5                  4015
#define IDC_RADIO17                     4016
#define IDC_CHECK_PIO0                  4016
#define IDC_RADIO18                     4017
#define IDC_CHECK_PIO6                  4017
#define ID_CONFIGHUB                    32771
#define ID_MAKEPRELOADIMAGE             32772
#define IDC_BUTTONSETFONTSIZE           32774
#define IDC_CHKCapacity                 32776
#define IDC_CHKVIDPID                   32777
#define IDC_CHKInquiry                  32778
#define IDC_CHKSerialNumber             32779
#define IDC_CHKWriteProtect             32780
#define IDC_CHKFlashID                  32781
#define IDC_CHKStatus                   32782
#define IDC_CHKBadBlock                 32784
#define IDC_BUTTONHIDE                  32785
#define IDC_CHECKENABLE332SETTING       32787
#define IDC_BUTTON_SETUPBTNNUM          32788
#define IDC_CHKProgress                 32789
#define IDC_DISKPARTITION               32790
#define IDC_ExtraSetting                32790
#define IDC_LISTHIDE                    32791
#define IDC_DecodeFile                  32792
#define IDC_LISTCOLRESIZE               32793
#define IDC_CreateDiskImg               32794
#define IDC_COMPortConnect              32797
#define IDC_MultipleEraseAll            32798
#define IDC_SupervisorMode              32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1581
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
